#  kubectl apply -f service-sa-logic.yaml --record
apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-logic
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate:
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:                                               # 6
    metadata:
      labels:
        app: sa-logic                                  # 7
    spec:
      containers:
        - image: rinormaloku/sentiment-analysis-logic
          imagePullPolicy: Always
          name: sa-logic
          ports:
            - containerPort: 5000
